name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env.dev file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.dev
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env.dev
        echo "POSTGRES_ENGINE=${{ secrets.POSTGRES_ENGINE }}" >> .env.dev
        echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> .env.dev
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.dev
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.dev
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env.dev
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env.dev
        echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env.dev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and run Docker containers
      run: |
        docker-compose -f path/to/your/docker-compose.yml up --build -d
        docker-compose -f path/to/your/docker-compose.yml run app sh -c "python manage.py test"
        docker-compose -f path/to/your/docker-compose.yml down
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        POSTGRES_ENGINE: ${{ secrets.POSTGRES_ENGINE }}
        POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
