name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd pill4chill
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Verify environment variables
      run: |
        echo "SECRET_KEY is set"
        echo "DEBUG: ${{ secrets.DEBUG }}"
        echo "POSTGRES_ENGINE: ${{ secrets.POSTGRES_ENGINE }}"
        echo "POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}"
        echo "POSTGRES_USER: ${{ secrets.POSTGRES_USER }}"
        echo "POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}"
        echo "POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}"
        echo "ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}"
    - name: Run Tests
      run: |
        cd pill4chill
        python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        POSTGRES_ENGINE: ${{ secrets.POSTGRES_ENGINE }}
        POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
