name: Python Style Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort diff-cover

      - name: Run flake8 on diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.patch
          diff-quality --violations=flake8 diff.patch

      - name: Check with black
        run: |
          black --check --diff .

      - name: Check imports with isort
        run: |
          isort --check-only --diff .
